# Generated by Django 5.0.7 on 2024-08-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(auto_now_add=True)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='journal_images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='journal_videos/')),
                ('voice_note', models.FileField(blank=True, null=True, upload_to='journal_voice_notes/')),
                ('gif', models.ImageField(blank=True, null=True, upload_to='journal_gifs/')),
            ],
        ),
    ]
