# Generated by Django 5.0.7 on 2024-08-06 05:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='entry_date',
        ),
        migrations.AddField(
            model_name='journal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
