# Generated by Django 5.0.7 on 2024-08-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
